'use client';
import { useState } from 'react';
import LogrosCard from '@/app/components/logrosCard';
import ControversiaCard from '@/app/components/controvCard';
import LogConBtn from '@/app/components/logConBtn';
import Kast from '../../../public/Kast1.webp';
export default function kastInfo() {

  return (
        <div className="min-h-screen bg-slate-50">
                {/* Header con imagen principal */}
                <header className="relative h-64 bg-slate-800">
                    <img 
                    src={Kast.src}
                    alt="Chile - Elecciones 2025"
                    className="w-full h-full object-cover opacity-40"
                    />
                        
                <div className="absolute inset-0 flex items-center justify-center">
                        <div className="text-center text-white">
                            <h1 className="text-5xl font-bold mb-2">
                            Vota Informa 2025
                            </h1>
                            <p className="text-xl">
                            Segunda Vuelta Presidencial
                            </p>
                    </div>
                </div>
            </header>

        <LogConBtn>
          <LogrosCard titulo="Las propuestas de José Antonio Kast (Entorno a la economía), el ultraconservador que busca llegar a La Moneda en su tercer intento" descripcion="El republicano ha marcado el debate económico con dos propuestas que han sido criticadas tanto por el oficialismo como por la derecha tradicional. Una de las más controversiales es el recorte fiscal de 6.000 millones de dólares en 18 meses. Kast no ha detallado la fórmula que usará para concretar el ajuste, aunque ha planteado que tomará medidas para reducir los gastos como terminar con los apitutados [funcionarios que han conseguido sus puestos mediante influencias] y con la regulación en la entrega de licencias médicas. En pensiones, el candidato ha dicho que impulsará el chao préstamo, una medida que pretende terminar con el préstamo del 1,5% de las personas al Estado que se ha definido en la reforma previsional impulsada por la Administración de Boric. El ultra ha insistido su propuesta de reducción de gastos no afectará la entrega de los beneficios sociales, entre ellos la Pensión Garantizada Universal (PGU) —en su campaña ha difundido la frase Te amo PGU para enfatizar su intención de mantener el beneficio—. En materia tributaria el candidato ha prometido eliminar las contribuciones [el impuesto territorial] a la primera vivienda." fuente="ElPaís.com" link="https://elpais.com/chile/2025-11-16/las-propuestas-de-jose-antonio-kast-el-ultraconservador-que-busca-llegar-a-la-moneda-en-su-tercer-intento.html" logro={true}/>

          <LogrosCard titulo="Las propuestas de José Antonio Kast (Entorno a la Seguridad), el ultraconservador que busca llegar a La Moneda en su tercer intento" descripcion="Kast ha presentado el Plan Implacable, una propuesta que, de acuerdo al candidato busca frenar el avance del crimen organizado en el país. “Chile está funcionando al revés: los delincuentes están libres y los ciudadanos honestos viven encerrados. El Plan Implacable es la respuesta firme que millones de chilenos estaban esperando”, ha dicho. Entre las iniciativas de este plan se encuentra la instalación de cárceles de máxima seguridad y aislamiento total para cabecillas narcos; el fin de los narcofunerales; endurecimiento de las penas para los integrantes de las bandas criminales; una revisión de la aplicación de la legítima defensa — poner fin a la “criminalización de víctimas que se defienden”, según el abanderado—; y crear una fuerza de tarea para la recuperación de las zonas ocupadas por la criminalidad. El ultraconservador es opositor a la pena de muerte y ha dicho que la pena más dura que debe enfrentar una persona es la cadena perpetua."
          fuente="ElPaís.com" link="https://elpais.com/chile/2025-11-16/las-propuestas-de-jose-antonio-kast-el-ultraconservador-que-busca-llegar-a-la-moneda-en-su-tercer-intento.html" logro={true}/>
          <LogrosCard titulo="Participación Politica Local" descripcion="Su trayectoria política se inicia con su ingreso a la Escuela de Derecho de la Pontificia Universidad Católica. Los años 1986 y 1987 integró el Consejo Superior de esa casa de estudios. Además, fue candidato a la presidencia de la Federación de Estudiantes (FEUC). También formó parte del Centro de Alumnos de la Escuela de Derecho, donde conoció a Jaime Guzmán, quien lo motivó para militar en la Unión Demócrata Independiente (UDI)" fuente="Biblioteca del Congreso Nacional de Chile" link="https://www.bcn.cl/historiapolitica/resenas_parlamentarias/wiki/José_Antonio_Kast_Rist" logro={true}/>

          <ControversiaCard titulo="Cuando fue diputado: Kast intervino en históricos temas de educación sin transparentar que era dueño de un colegio" descripcion="Recién el pasado 10 de septiembre, después que Interferencia revelara los antecedentes, se supo públicamente que el aludido es propietario desde 1998 y hasta la fecha del Colegio Campanario de Buin. Esto a través de la sociedad Inmobiliaria e Inversiones Padua, la cual también integra su esposa, María Pía Adriasola, quien es parte del directorio del establecimiento que en 2021 tuvo utilidades por $180 millones. Kast fue diputado entre 2002 y 2018, período en el cual participó en la legislación de temas educacionales en reiteradas ocasiones: 14 mociones (dos terminaron en ley), 5 indicaciones, 14 proyectos de acuerdo, 1 proyecto de resolución, 45 intervenciones, 63 peticiones de oficios. Asimismo, fue parte de numerosas votaciones (cuyo número exacto no fue posible determinar por errores de la web de la Cámara de Diputados) en temas relevantes que afectaron al sistema escolar en general, tanto al privado como a la competencia de su negocio, la educación pública." contexto="El candidato presidencial del Partido Republicano, José Antonio Kast, mientras era diputado, estuvo años legislando en materia educacional sin transparentar un conflicto de intereses relevante: él junto con su familia eran dueños de un privilegiado colegio particular pagado" fuente="Interferencia.cl" link="https://interferencia.cl/articulos/cuando-fue-diputado-kast-intervino-en-historicos-temas-de-educacion-sin-transparentar-que" controversia={true}/>

          <ControversiaCard titulo='Kast explica por qué fue el único en votar en contra de la Ley Cholito: "Era una mala ley"' descripcion='“A mí alguna vez me acusaron de votar en contra de una ley y fui el único, porque que era una mala ley. Era una mala ley que, por presión, otros colegas míos no se atrevieron a levantar la voz”, aseguró el candidato. 
          Kast explica por qué voto en contra de la Ley Cholito. 
          Pero esa normativa, continuó el abanderado republicano, “no le solucionó los problemas a aquellos animalitos que nos acompañan en nuestras casas. Aquellos animalitos que están abandonados aquí en el paseo peatonal de Antofagasta. Aquellos animalitos que hoy día son comunes, pero no son de nadie y viven en el abandono”.' fuente='BioBioChile' link='https://www.biobiochile.cl/noticias/nacional/chile/2025/08/18/kast-explica-por-que-fue-el-unico-en-votar-en-contra-de-la-ley-cholito-era-una-mala-ley.shtml' controversia={true} contexto='En la misma instancia de campaña'/>

          <ControversiaCard titulo='Las propuestas de José Antonio Kast, el ultraderechista que busca gobernar Chile con "mano dura" contra la migración' descripcion='Seguridad como eje central Kast presentó el Plan Implacable, una propuesta enfocada en enfrentar al crimen organizado y “restablecer el orden”, según su plataforma de campaña. “Chile está funcionando al revés: los delincuentes están libres y los ciudadanos honestos viven encerrados”, dice, y afirma que su proyecto pretende revertir ese escenario. Entre las principales medidas del plan, Kast propone construir cárceles de máxima seguridad con aislamiento total para líderes del narcotráfico, prohibir los narcofunerales, endurecer penas para las bandas criminales y desplegar una fuerza de tarea especial para recuperar áreas dominadas por la delincuencia.
          Migración: deportaciones masivas y vuelos chárter Kast propone convertir la migración irregular en un delito, limitar beneficios públicos en salud, educación y vivienda para migrantes sin documentos e impulsar un plan de expulsiones de gran escala. “El año más exitoso de expulsiones va a ser el año 2026 después de que nosotros asumamos el gobierno”, afirmó durante el debate en T13. Su enfoque ha sido comparado con el Trump, con quien Kast ha mostrado afinidad simbólica y política. Durante su cierre de campaña en Viña del Mar apareció detrás de un vidrio blindado, replicando la protección que utiliza el presidente de Estados Unidos. En su discurso ese mismo día, dijo: “Vamos a cerrar las fronteras, le vamos a exigir a esas 300.000 personas que entraron de manera irregular que dejen nuestra patria”.
          ' fuente='CNN Latinoamérica' link='https://cnnespanol.cnn.com/2025/11/15/latinoamerica/propuestas-jose-antonio-kast-ultraderechista-chile-orix' controversia={true} contexto='José Antonio Kast, líder de la ultraderecha y fundador del Partido Republicano, disputa la presidencia de Chile por tercera vez con un mensaje de “mano dura” centrado en seguridad y migración.'/>

        <ControversiaCard titulo='Recorte fiscal' contexto='Fue a mediados de julio cuando desde el equipo de Kast anunciaron un recorte de gasto fiscal por US$ 6 mil millones en solo un año y medio.' descripcion='La medida se convirtió en un hito de la campaña del republicano, quien la refrendó en público en debates y seminarios, pero también se ha transformado en una suerte de propuesta incómoda al interior del comando y blanco recurrente de críticas del oficialismo y también de Chile Vamos.' fuente='LaTercera' link='https://www.latercera.com/politica/noticia/batalla-digital-errores-no-forzados-y-propuestas-polemicas-los-momentos-que-marcaron-la-cruzada-presidencial' controversia={true}/>

        <ControversiaCard titulo='Cruces con Boric' contexto='A lo largo de la carrera por llegar a La Moneda, el republicano ha tenido varios cruces con el Presidente Gabriel Boric.' descripcion='Ambos se han lanzado sus dardos. Uno de los más recordados corresponde a cuando el Mandatario en plena cadena nacional sobre el Presupuesto criticó la propuesta de ajuste fiscal de Kast, quien al rato salió a responder por X, para el día siguiente elevar el tono en un punto de prensa.' fuente='LaTercera' link='https://www.latercera.com/politica/noticia/batalla-digital-errores-no-forzados-y-propuestas-polemicas-los-momentos-que-marcaron-la-cruzada-presidencial' controversia={true}/>

        <ControversiaCard titulo='Podio de vidrio' contexto='En uno de los actos de cierre de campaña Kast hizo una puesta en escena que captó la atención.' descripcion='En Viña del Mar, el candidato se posó en un podio cubierto por un cristal antibalas que generó diversas reacciones del mundo político.' fuente='LaTercera' link='https://www.latercera.com/politica/noticia/batalla-digital-errores-no-forzados-y-propuestas-polemicas-los-momentos-que-marcaron-la-cruzada-presidencial' controversia={true}/>
        
        <ControversiaCard titulo='Jara acusa a Kast de escapar de los debates: republicano desestima críticas y prioriza despliegue territorial' contexto='El candidato presidencial del Partido Republicano, José Antonio Kast, desestimó los emplazamientos de la abanderada del pacto Unidad por Chile, Jeannette Jara, para debatir, asegurando que nunca existió un acuerdo concreto para un encuentro televisivo este domingo.Frente a las críticas por su inasistencia, Kast afirmó que prefiere priorizar el despliegue territorial. “Si hay alguien que no asistió a los debates, porque los perdió todos, fue Jeannette Jara. Hay dos debates que se han planteado y que nosotros siempre vamos a estar disponibles, que es el de Archi y Anatel. Yo no tengo agendado ningún debate para el domingo, ninguno, porque ese es un debate que se acordó con una candidata, ella dijo, y ella ha hecho un emplazamiento, pero para debatir se necesitan dos”, planteó el republicano.' descripcion='"Sé que no quiere ir, porque la otra vez perdió en la segunda vuelta en los debates”, afirmó la candidata, quien además cargó contra el historial del asesor económico de su adversario, Jorge Quiroz, involucrado en la colusión de los pollos' controversia={true} fuente="DiarioUChile" link="https://radio.uchile.cl/2025/11/19/jara-acusa-a-kast-de-escapar-de-los-debates-republicano-desestima-criticas-y-prioriza-despliegue-territorial/"/>
        
        <ControversiaCard titulo="RECONOCIMIENTO Y PROTECCIÓN AL DERECHO A LA IDENTIDAD DE GÉNERO" contexto="SEGUNDO TRÁMITE CONSTITUCIONAL. BOLETÍN N° 8924-07" descripcion="Señor Presidente, en primer lugar, nadie merece ser discriminado y nadie merece morir, bajo ninguna circunstancia. Pero eso es muy distinto a decir que la dignidad y la inclusión se imponen por ley. Ambas se reconocen y nacen en la sociedad, pero no se imponen a través de una ley, como se propone en este proyecto, que establece sanciones ante ciertas situaciones que son realmente insólitas." controversia={true} fuente="Biblioteca del Congreso Nacional de Chile" link="https://www.bcn.cl/laborparlamentaria/participacion?idParticipacion=2130956&idPersona=2231&idDocumento=683551&idAkn=akn683551-po1-ds370-ds381"/>
        </LogConBtn>


      </div>
    );
}