'use client';
import { useState } from 'react';
import Jeannette from '../../../public/Jara1.webp';
import LogConBtn from '@/app/components/logConBtn';
import ControversiaCard from '@/app/components/controvCard';
import LogrosCard from '@/app/components/logrosCard';
export default function jannetteInfo() {
    
    return (
        <div className="min-h-screen bg-slate-50">
                {/* Header con imagen principal */}
                <header className="relative h-64 bg-slate-800">
                    <img 
                    src={Jeannette.src}
                    alt="Chile - Elecciones 2025"
                    className="w-full h-full object-cover opacity-40"
                    />
                        
                <div className="absolute inset-0 flex items-center justify-center">
                        <div className="text-center text-white">
                            <h1 className="text-5xl font-bold mb-2">
                            Vota Informa 2025
                            </h1>
                            <p className="text-xl">
                            Segunda Vuelta Presidencial
                            </p>
                    </div>
                </div>
            </header>
        <LogConBtn>
            <LogrosCard logro={true} titulo="Reducción de la jornada laboral" descripcion="Además de reducir en forma gradual la jornada laboral de 45 a 40 horas semanales, en cinco años, incluye medidas de corresponsabilidad que apuntan a conciliar la vida laboral, personal y familiar, como las bandas horarias, que permiten diferir el ingreso y salida del trabajo para adecuarlo a los horarios escolares, por ejemplo." fuente="Ministerio del Trabajo y Prevensión Social" link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio"/>
            
            <LogrosCard logro={true} titulo="Aumento del sueldo mínimo" descripcion="Reajusta el monto del ingreso mínimo mensual con la siguiente gradualidad: un incremento desde $410.000 a $440.000 el 1 de mayo de 2023; luego, a $460.000 el 1 de septiembre de 2023; y, posteriormente, a $500.000 el 1 de julio de 2024. Además, aumenta el universo de beneficiarios y beneficiarias de la asignación familiar y maternal, y extiende el Ingreso Mínimo Garantizado y el subsidio temporal a las micro, pequeñas y medianas empresas." fuente="Ministerio de Trabajo y Prevensión Social" link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio"/>

            <LogrosCard logro={true} titulo="Conciliación Vida Personal, Familiar y Laboral" descripcion="Entre otras medidas de adecuación relacionadas a los lineamientos del Convenio 190 de la OIT sobre violencia y acoso en el trabajo, el proyecto establece, como obligación de las empresas y de los órganos del Estado, un protocolo de prevención del acoso laboral y/o sexual y la violencia en el trabajo, reforzando un enfoque preventivo que estaba ausente en la regulación. Además, se avanzó en el perfeccionamiento de los procesos de investigación del acoso sexual y se incorporaron a la regulación las conductas de acoso laboral y la violencia en el trabajo." fuente="Ministerio del Trabajo y Prevensión Social" link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio"/>

            <LogrosCard logro={true} titulo="Fortalece la legislación contra el acoso sexual, laboral y violencia en el trabajo" descripcion="Entre otras medidas de adecuación relacionadas a los lineamientos del Convenio 190 de la OIT sobre violencia y acoso en el trabajo, el proyecto establece, como obligación de las empresas y de los órganos del Estado, un protocolo de prevención del acoso laboral y/o sexual y la violencia en el trabajo, reforzando un enfoque preventivo que estaba ausente en la regulación. Además, se avanzó en el perfeccionamiento de los procesos de investigación del acoso sexual y se incorporaron a la regulación las conductas de acoso laboral y la violencia en el trabajo." fuente="Ministerio del Trabajo y Prevensión Social" link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio"/>

            <LogrosCard logro={true} titulo="Promulga el Convenio 190 sobre la violencia y el acoso de la Organización Internacional del Trabajo (OIT)" descripcion="Es la primera normativa internacional que aborda las problemáticas en el mundo del trabajo, mediante un instrumento específico referido a las normas que regulan las relaciones laborales. Según lo indicado por la OIT, se debe aplicar a todos los sectores de la economía, público o privado, formal e informal, en zonas urbanas o rurales, y cualquiera sea la situación contractual de las y los trabajadores. El convenio agrupa la igualdad y la no discriminación, con la seguridad y salud en el trabajo en un solo instrumento y sitúa la dignidad humana y el respeto en su centro. En ese sentido, reconoce que la violencia y el acoso pueden constituir una violación o abuso de los derechos humanos y prevé, por primera vez, un único concepto compuesto de violencia y acoso." fuente="Ministerio del Trabajo y Prevensión Social" link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio"/>

            <LogrosCard logro={true} titulo="Fortalece el Seguro de Cesantía" descripcion="Mejora los beneficios y flexibiliza el acceso a las prestaciones del Seguro de Cesantía y, además, permite financiar programas de intermediación laboral con hasta el 2% del Fondo de Cesantía Solidario." fuente="Ministerio de Trabajo y Prevensión Social" link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio"/>

            <LogrosCard logro={true} titulo="Ampliación y mejora de la cobertura de la ley Sanna" descripcion="Amplía, de 90 a 180 días, el plazo de permiso para las y los trabajadores que son padres de una niña o niño afectado por cáncer o trasplante de órgano sólido o de progenitores hematopoyéticos. Además, se incorpora la cobertura de una quinta contingencia: enfermedad grave de niña o niño de uno a cuatro años que requiera hospitalización en una Unidad de Cuidados Intensivos o de Tratamientos Intermedios (UCI-UTI)." fuente="Minsterio de Trabajo y Prevensión Social" link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio"/>

            <LogrosCard logro={true} titulo="Reajuste remuneraciones Sector Público" descripcion="Establece un reajuste de remuneraciones del sector público, con un aumento de las remuneraciones de un 4,3%. Dicha cifra es resultado del acuerdo que se alcanzó con 15 organizaciones de la Mesa del Sector Público y se estima que beneficiará a cerca de 844.934 trabajadores." fuente="Minsterio de Trabajo y Prevensión Social" link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio"/> 

            <LogrosCard logro={true} titulo="Impulsa medidas para la seguridad económica" descripcion="Duplica el Aporte Familiar Permanente -exBono Marzo- de forma extraordinaria en 2023 a través de un aporte complementario, que beneficia a más de 3 millones de personas en una etapa del año con una alta carga económica. Las personas obtendrán su Aporte Familiar Permanente según las reglas generales, y, además, recibirán un segundo pago extraordinario por el mismo monto a partir del mes de este mismo mes, totalizando un beneficio de aproximadamente 120 mil pesos directo a su bolsillo. Además, fija una alza permanente en un 20% del Subsidio Único Familiar y la Asignación Familiar y Maternal a partir del mes de mayo de 2023." fuente="Minsterio de Trabajo y Prevensión Social" link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio"/>

            <LogrosCard logro={true} titulo="Convenio 176 de la OIT" descripcion="Duplica el Aporte Familiar Permanente -exBono Marzo- de forma extraordinaria en 2023 a través de un aporte complementario, que beneficia a más de 3 millones de personas en una etapa del año con una alta carga económica. Las personas obtendrán su Aporte Familiar Permanente según las reglas generales, y, además, recibirán un segundo pago extraordinario por el mismo monto a partir del mes de este mismo mes, totalizando un beneficio de aproximadamente 120 mil pesos directo a su bolsillo. Además, fija una alza permanente en un 20% del Subsidio Único Familiar y la Asignación Familiar y Maternal a partir del mes de mayo de 2023." fuente="Minsterio de Trabajo y Prevensión Social" link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio"/>

            <LogrosCard logro={true} titulo="Reajusta el Ingreso Mínimo Mensual" descripcion="Reajusta el monto del ingreso mínimo mensual, así como la asignación familiar y maternal, y el subsidio familiar, otorga un subsidio temporal a las micro, pequeñas y medianas empresas en la forma que indica, y establece un aporte compensatorio del aumento del valor de la canasta básica de alimentos." fuente="Minsterio de Trabajo y Prevensión Social" link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio"/>

            <LogrosCard logro={true} titulo="Ley 21.474 | Crea bono extraordinario" descripcion="Crea un bono extraordinario chile apoya de invierno y extiende el permiso postnatal parental." fuente="Ministerio de Trabajo y Prevensión Social" link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio"/>

            <LogrosCard logro={true} titulo="Ley 21.476 |  Asegura Transporte en elecciones o plebiscitoss" descripcion="Ley 21476 modifica el código del trabajo para asegurar la oferta de servicios de transporte público durante periodo de elecciones populares o plebiscitos." link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio" fuente="Ministerio de Trabajo y Prevensión Social"/>

            <LogrosCard logro={true} titulo="Ley 21.471 | Condona intereses moratorios de créditos prendarios" descripcion="Ley 21471 Modifica el decreto con fuerza de ley n° 16, de 1986, del ministerio del trabajo y previsión social, con el objeto de facultar temporalmente al director(a) general del crédito prendario para condonar intereses moratorios de créditos pignoraticios que se hubieren devengado durante el período que indica." link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio" fuente="Ministerio de Trabajo y Prevensión Social"/>

            <LogrosCard logro={true} titulo="Ley 21.482 | Declara feriado nacional" descripcion="Ley 21482 declara feriado nacional el día 16 de septiembre del año 2022." link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio" fuente="Ministerio de Trabajo y Prevensión Social"/>

            <LogrosCard logro={true} titulo="Ley 21.510 | Extiende permiso postnatal" descripcion="Ley 21510 extiende transitoriamente el permiso postnatal parental." link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio" fuente="Ministerio de Trabajo y Prevensión Social"/>

            <LogrosCard logro={true} titulo="Ley 21.526 | Reajuste sector público" descripcion="Ley 21526 otorga reajuste de remuneraciones a las y los trabajadores del sector público, concede aguinaldos que señala, concede otros beneficios que indica, y modifica diversos cuerpos legales." link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio" fuente="Ministerio de Trabajo y Prevensión Social"/>

            <LogrosCard logro={true} titulo="Ley 21.538 | Ampliación de beneficiarios de la PGU" descripcion="Ley 21538 modifica la ley n°21.419, que crea la pensión garantizada universal y modifica los cuerpos legales que indica." link="https://www.mintrab.gob.cl/leyes-aprobadas-por-ministerio" fuente="Ministerio de Trabajo y Prevensión Social"/>

            <LogrosCard logro={true} titulo="Seguridad: golpear las finanzas del crimen organizado" descripcion='La seguridad se ha convertido en el tema dominante del debate electoral. Jara, a través de su propuesta Plan Chile Seguro, plantea levantar el secreto bancario —una norma que protege la privacidad de las transacciones financieras de las personas— para rastrear el flujo de dinero vinculado al narcotráfico. Además, busca fortalecer a Carabineros y a la Policía de Investigaciones (PDI) y emplear tecnologías como drones e inteligencia artificial para mejorar la vigilancia territorial. “No basta con más cárceles o más carabineros si no enfrentamos de raíz al crimen organizado. Porque ellos no vienen por ideología, vienen por plata. Y para frenarlos, hay que golpear donde más les duele: sus recursos”, explica Jara en uno de sus videos de campaña en redes sociales.' fuente="CNN Latinoamérica" link="https://cnnespanol.cnn.com/2025/11/15/latinoamerica/propuestas-jeanette-jara-chile-orix"/>

            <LogrosCard logro={true} titulo="Jara y su propuesta de seguro veterinario estatal y clínicas públicas para mascotas en Chile" descripcion="El plan presentado por Jeannette Jara no solo representa una innovación en la atención veterinaria, sino también una oportunidad para alcanzar una mayor comprensión de la importancia de la salud animal en el contexto social y ambiental. A través de medidas claras y objetivos bien definidos, Jara busca transformar la forma en que Chile se relaciona con sus mascotas, promoviendo un futuro más seguro y solidario." fuente="The Times" link="https://thetimes.cl/contenido/8323/jara-y-su-propuesta-de-seguro-veterinario-estatal-y-clinicas-publicas-para-masco" />

            <LogrosCard logro={true} titulo="Infancias libres, futuro seguro." descripcion="Crearemos un Sistema Nacional de Protección Administrativa para niñas, niños y adolescentes, extendiendo Chile Crece Contigo hasta los 13 años y la atención pediátrica en el sistema público hasta los 18 años.Garantizaremos el acceso universal a tecnologías de la información propondremos el derecho a voto desde los 16 años y reformaremos la Ley de Municipalidades y el Servicio de Protección Especializada para fortalecer la participación, protección y bienestar de niñas, niños y adolescentes." fuente="Prioridades Plataforma" link="https://www.servel.cl/wp-content/uploads/2025/05/2-JEANNETTE-JARA-ROMAN.pdf"/>

            <ControversiaCard titulo='“No hay más esfuerzo fiscal”: Jara descarta gratuidad universal, pero propone extender beneficio al 70% más vulnerable' descripcion="La candidata presidencial también destacó la idea de regular las prácticas profesionales bajo la Ley Karin." fuente="LaTercera" link="https://www.latercera.com/politica/noticia/no-hay-mas-esfuerzo-fiscal-jara-descarta-gratuidad-universal-pero-propone-extender-beneficio-al-70-mas-vulnerable" controversia={true} contexto="Jeannette Jara, descartó que bajo su gobierno promueva la gratuidad universal en educación superior debido a las limitaciones de recursos fiscales. Sin embargo, planteó la extensión del beneficio estudiantil para el 70% de la población más vulnerable.Hasta ahora, la beca que cubre la totalidad de los aranceles de educación superior abarca a las familias que pertenecen al 60% de menores ingresos. Y pese a que la exministra afirmó que no es posible lograr una cobertura del 100%, señaló que de todas formas su objetivo es “avanzar” a más beneficiarios."/>
        
            <ControversiaCard titulo='“Es inaceptable”: Jeannette Jara recibe críticas transversales por declaraciones sobre Cuba y Venezuela' descripcion='La abanderada del PC sostuvo que en el país gobernado por Nicolás Maduro hay un “régimen autoritario”, mientras que en el otro existe un "sistema democrático diferente al nuestro". Tohá y Winter marcaron diferencias con esas posturas. -Fernanda Araneda' contexto='Polémica provocaron los dichos de la candidata presidencial del Partido Comunista (PC), Jeannette Jara, sobre la situación en la que se encuentra Cuba. La exministra del Trabajo descartó que haya una dictadura en ese país, lo que generó reacciones de sus contrincantes en las primarias del oficialismo y también en la oposición. “Creo que Cuba tiene un sistema democrático distinto del nuestro. Hay un partido único, no es el único sistema así, cada pueblo tiene que definir su gobierno”, dijo en conversación con CNN Chile. Asimismo, la ex ministra del Trabajo también fue requerida sobre su opinión de Venezuela, país donde aseguró, hay un “régimen autoritario”. Consultada sobre estas declaraciones, la ex ministra del Interior y candidata presidencial del PPD, Carolina Tohá, afirmó que en este tema tiene una diferencia con Jara, pues a su juicio el sistema cubano “no cumple con ninguno de los requisitos de una democracia”.' controversia={true} fuente="Diario Uchile" link="https://radio.uchile.cl/2025/04/10/ es-inaceptable-jeannette-jara-recibe-criticas-transversales-por-declaraciones-sobre-cuba-y-venezuela"/>

            <ControversiaCard controversia={true} titulo='El debate por la “descomunización” de la candidata Jeannette Jara' descripcion="Respecto a las declaraciones de Daniel Jadue y la eventual suspensión de militancia por parte de Jeannette Jara, Barraza enfatizó que “es inadecuado, no es correcto. Convierte en controversia una medida que podría haber sido un gran anuncio, o que va a ser un gran anuncio, en el entendido que Jeannette Jara es la candidata del conjunto de la centro izquierda y el progresismo en Chile y, como tal, representa una coalición en desarrollo que es plural en términos de composición pero que tiene propósitos comunes. Por lo mismo, tiene el desafío de ganar las próximas elecciones presidenciales y tiene el desafío de construir un nuevo conglomerado político social que enfrente el periodo y permita continuar con las transformaciones y la gobernabilidad en Chile”. En esa línea, agregó que “coincido que la palabra 'descomunizar' es una palabreja, el que Jeannette anuncie -y le corresponde a ella, no a otra persona- congelar o suspender la militancia, lejos de estar en el plano de la 'descomunización' está en las señales de amplitud para interpretar al conjunto de la ciudadanía”. Asimismo, sobre las intervenciones de Jadue y de Lautaro Carmona respecto a la campaña de Jeannette Jara, Larraín planteó que “uno se pregunta cuál es la cohesión del PC detrás de Jara y se está notando en la campaña. Es evidente que Jara, que es del PC, que tiene una trayectoria e historia en el partido, se está moviendo hacia el centro, está buscando conectarse con grandes mayorías, es una buena pregunta saber quién es realmente más allá del personaje, cuál es el proyecto político que ella va a llevar adelante”. Además, añadió que “la derecha chilena apoyó a una dictadura que violó los Derechos Humanos y somos muchos los que tenemos una mirada crítica de eso y lo hemos entendido como un aprendizaje para que no vuelva a ocurrir. Yo me pregunto si hay un aprendizaje en el apoyo a diversos regímenes comunistas brutales que hay en el mundo, los cuales el Partido Comunista sigue apoyando. Quien dijo que Jara era marxista fue un senador del propio partido y habrá que preguntarse cuál es la naturaleza del compromiso democrático cuando alguien se declara marxista”."
             contexto='En Columnistas de Mesa Central, Iván Valenzuela conversó con Hernán Larraín y Marcos Barraza sobre la militancia de Jeannette Jara en el Partido Comunista y su eventual suspensión de cara a la carrera presidencial.' fuente="Tele13" link="https://tele13radio.cl/article/el-debate-por-la-descomunizacion-de-la-candidata-jeannette-jara"/>

             <ControversiaCard titulo='Error con su programa' contexto='La candidata oficialista y de la DC se vio envuelta en una controversia a propósito de su programa inicial de gobierno, específicamente por la iniciativa de nacionalización del cobre.' descripcion='En agosto, en un debate organizado por el gremio del transporte, el candidato republicano José Antonio Kast la enfrentó por esta idea, la que fue negada por la exministra del Trabajo. “Aquí hay gente que dijo que en la primaria se habló de nacionalizar el cobre y eso jamás se tocó”, dijo Jara. Al día siguiente, el exdiputado dio cuenta de un párrafo de las bases programáticas de la abanderada que estaba inscrito en el Servicio Electoral (Servel) y que incluía la medida. Después de varios emplazamientos, la candidata admitió el error y privilegió una gira por el país, en desmedro de su asistencia en ese tipo de instancias.' fuente='LaTercera' link='https://www.latercera.com/politica/noticia/batalla-digital-errores-no-forzados-y-propuestas-polemicas-los-momentos-que-marcaron-la-cruzada-presidencial' controversia={true}/>

        </LogConBtn>

        <footer className="bg-slate-800 text-white py-8 mt-16">
            <div className="max-w-6xl mx-auto px-4 text-center">
            <p className="text-lg mb-2">© 2025 Vota Informa</p>
            <p className="text-slate-400 text-sm">
                Información electoral objetiva para Chile
            </p>
            </div>
      </footer>
    </div>
    );
}